### ISSUE TITLE
Redundant Schema Handling

### ISSUE THREAD

**Issue by luandy64** [lambtron/tap-toast#2]
`populate_class_schemas(catalog, selected_stream_names)` on [line 53 of `__init__.py`](https://github.com/lambtron/tap-toast/blob/4a48cf6eaf3a2909692be74921be05e0c3c98651/tap_toast/__init__.py#L57) 

and 

`instance.stream = stream` on [line 73 of `__init__.py`](https://github.com/lambtron/tap-toast/blob/4a48cf6eaf3a2909692be74921be05e0c3c98651/tap_toast/__init__.py#L73)

seem to clash?  If you do the thing on line 73, then `populate_class_schemas` is redundant

**Comment by lambtron** [comment]
https://github.com/lambtron/tap-toast/commit/7a6da79b8a87cc96b91ab2a2e2e96045169b75cf
